{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      nixpkgs,
      rust-overlay,
      treefmt-nix,
      ...
    }:
    let
      supportedSystems = [
        "x86_64-linux"
        "aarch64-linux"
        "aarch64-darwin"
      ];

      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f (
            let
              pkgs = import nixpkgs {
                inherit system;
                overlays = [ (import rust-overlay) ];
              };

              rust = pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml;

              # tau-ui (GPUI) links xcb and xkbcommon, and loads Vulkan,
              # Wayland and X11 at runtime.
              guiLibs = pkgs.lib.optionals pkgs.stdenv.isLinux (
                with pkgs;
                [
                  fontconfig
                  freetype
                  libx11
                  libxcb
                  libxcursor
                  libxi
                  libxkbcommon
                  libxrandr
                  vulkan-loader
                  wayland
                ]
              );

              rustPlatform = pkgs.makeRustPlatform {
                cargo = rust;
                rustc = rust;
              };

              tau-ui = rustPlatform.buildRustPackage {
                pname = "tau-ui";
                version = "0.1.0";

                src = pkgs.lib.fileset.toSource {
                  root = ./.;
                  fileset = pkgs.lib.fileset.unions [
                    ./Cargo.toml
                    ./Cargo.lock
                    ./crates
                  ];
                };

                cargoLock.lockFile = ./Cargo.lock;
                cargoBuildFlags = [
                  "--package"
                  "tau-ui"
                ];
                cargoTestFlags = [
                  "--package"
                  "tau-ui"
                ];

                # The sqlx query metadata is committed; no database at build time.
                SQLX_OFFLINE = "true";

                nativeBuildInputs = [
                  pkgs.pkg-config
                  pkgs.makeWrapper
                ];
                buildInputs = guiLibs;
                # The tests make fixture repositories with git; the app
                # itself does not need it.
                nativeCheckInputs = [ pkgs.git ];

                # GPUI opens Vulkan, Wayland and X11 with dlopen, so the
                # binary needs them on its library path.
                postFixup = ''
                  wrapProgram $out/bin/tau-ui \
                    --prefix LD_LIBRARY_PATH : ${pkgs.lib.makeLibraryPath guiLibs}
                '';

                meta = {
                  description = "A GPUI interface for tau agents";
                  mainProgram = "tau-ui";
                  platforms = pkgs.lib.platforms.linux;
                };
              };

              formatter =
                (treefmt-nix.lib.evalModule pkgs {
                  projectRootFile = "flake.nix";

                  settings = {
                    allow-missing-formatter = true;
                    verbose = 0;

                    global.excludes = [
                      "*.lock"
                      # Generated by `cargo sqlx prepare`; formatting it causes churn.
                      "crates/*/.sqlx/*"
                    ];

                    formatter = {
                      nixfmt.options = [ "--strict" ];

                      rustfmt = {
                        package = rust;

                        options = [
                          "--config-path"
                          (toString ./rustfmt.toml)
                        ];
                      };
                    };
                  };

                  programs = {
                    nixfmt.enable = true;
                    oxfmt.enable = true;
                    rustfmt = {
                      enable = true;
                      package = rust;
                    };
                    taplo.enable = true;
                  };
                }).config.build.wrapper;
            in
            {
              inherit
                formatter
                guiLibs
                pkgs
                rust
                system
                tau-ui
                ;
            }
          )
        );
    in
    {
      formatter = forEachSupportedSystem ({ formatter, ... }: formatter);

      packages = forEachSupportedSystem (
        { pkgs, tau-ui, ... }:
        pkgs.lib.optionalAttrs pkgs.stdenv.isLinux {
          inherit tau-ui;
          default = tau-ui;
        }
      );

      apps = forEachSupportedSystem (
        { pkgs, tau-ui, ... }:
        pkgs.lib.optionalAttrs pkgs.stdenv.isLinux {
          default = {
            type = "app";
            program = pkgs.lib.getExe tau-ui;
          };
        }
      );

      devShells = forEachSupportedSystem (
        {
          pkgs,
          rust,
          formatter,
          guiLibs,
          ...
        }:
        {
          default = pkgs.mkShell {
            name = "tau-agent";

            buildInputs =
              with pkgs;
              [
                formatter
                rust

                bacon
                cargo-deny
                cargo-mutants
                cargo-nextest
                cargo-watch

                curl
                jq
                sqlx-cli
              ]
              ++ guiLibs;

            nativeBuildInputs = [ pkgs.pkg-config ];

            LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath guiLibs;
          };
        }
      );
    };
}
